In [ ]:
"""TO - DO - Task"""

In [22]:
# Task-1

def meters_to_feet(meters):
    """Converts meters to feet."""
    return meters * 3.28084

def feet_to_meters(feet):
    """Converts feet to meters."""
    return feet / 3.28084

def kg_to_lbs(kg):
    """Converts kilograms to pounds."""
    return kg * 2.20462

def lbs_to_kg(lbs):
    """Converts pounds to kilograms."""
    return lbs / 2.20462

def liters_to_gallons(liters):
    """Converts liters to gallons."""
    return liters * 0.264172

def gallons_to_liters(gallons):
    """Converts gallons to liters."""
    return gallons / 0.264172

def get_conversion(choice, value):
    """Performs the selected conversion."""
    conversions = {
        '1': meters_to_feet,
        '2': feet_to_meters,
        '3': kg_to_lbs,
        '4': lbs_to_kg,
        '5': liters_to_gallons,
        '6': gallons_to_liters
    }
    
    if choice in conversions:
        return conversions[choice](value)
    else:
        return None

def main():
    """Main function to handle user input and perform conversions."""
    print("Unit Converter: Choose a conversion type")
    print("1: Meters to Feet")
    print("2: Feet to Meters")
    print("3: Kilograms to Pounds")
    print("4: Pounds to Kilograms")
    print("5: Liters to Gallons")
    print("6: Gallons to Liters")
    
    choice = input("Enter your choice (1-6): ")
    
    try:
        value = float(input("Enter the value to convert: "))
        result = get_conversion(choice, value)
        
        if result is not None:
            print(f"Converted value: {result:.4f}")
        else:
            print("Invalid choice. Please select a number between 1 and 6.")
    except ValueError:
        print("Invalid input. Please enter a numeric value.")

if __name__ == "__main__":
    main()

Unit Converter: Choose a conversion type
1: Meters to Feet
2: Feet to Meters
3: Kilograms to Pounds
4: Pounds to Kilograms
5: Liters to Gallons
6: Gallons to Liters


Enter your choice (1-6):  4
Enter the value to convert:  41


Converted value: 18.5973


In [ ]:
#Task - 2:

In [8]:
def calculate_sum(numbers):
    """Returns the sum of the list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of the list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """Returns the maximum number from the list."""
    return max(numbers) if numbers else None

def find_minimum(numbers):
    """Returns the minimum number from the list."""
    return min(numbers) if numbers else None

def get_numbers():
    """Prompts the user to enter a list of numbers and returns them as a list."""
    try:
        user_input = input("Enter a list of numbers separated by spaces: ")
        numbers = list(map(float, user_input.split()))
        if not numbers:
            raise ValueError("The list cannot be empty.")
        return numbers
    except ValueError:
        print("Invalid input. Please enter numeric values only.")
        return None

def main():
    """Main function to handle user input and perform mathematical operations."""
    print("Mathematical Operations:")
    print("1: Sum")
    print("2: Average")
    print("3: Maximum")
    print("4: Minimum")
    
    choice = input("Enter your choice (1-4): ")
    numbers = get_numbers()
    
    if numbers is None:
        return
    
    operations = {
        '1': calculate_sum,
        '2': calculate_average,
        '3': find_maximum,
        '4': find_minimum
    }
    
    if choice in operations:
        result = operations[choice](numbers)
        print(f"Result: {result}")
    else:
        print("Invalid choice. Please select a number between 1 and 4.")

if __name__ == "__main__":
    main()


Mathematical Operations:
1: Sum
2: Average
3: Maximum
4: Minimum


Enter your choice (1-4):  2
Enter a list of numbers separated by spaces:  2 3 4 


Result: 3.0


In [ ]:
#4.2 Exercise on List Manipulation:

In [ ]:
1. Extract Every Other Element:

In [20]:
def extract_every_other(lst):
    """
    Extracts every other element from a given list, starting with the first element.

    Parameters:
        lst (list): The list from which elements will be extracted.

    Returns:
        list: A new list containing every other element from the original list.
    """
    # Take every second element from the list, starting from the first one
    result = lst[::2]
    return result

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
filtered_list = extract_every_other(example_list)

# Display the result
print("Original list:", example_list)
print("Every other element:", filtered_list)


Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


In [ ]:
2. Slice a Sublist:

In [24]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, starting from a specified index and ending at another specified index.

    Parameters:
        lst (list): The input list.
        start (int): The starting index (inclusive).
        end (int): The ending index (inclusive).

    Returns:
        list: A sublist from start to end (inclusive).
    """
    # Extract the sublist from start to end (inclusive)
    return lst[start:end+1]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4

sublist = get_sublist(example_list, start_index, end_index)

# Display the result
print("Original list:", example_list)
print(f"Sublist from index {start_index} to {end_index}:", sublist)


Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


In [ ]:
3. Reverse a List Using Slicing:


In [26]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list with elements in reverse order.
    """
    return lst[::-1]  # Slicing with step -1 reverses the list

# Example usage
example_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(example_list)

# Display the result
print("Original list:", example_list)
print("Reversed list:", reversed_list)


Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [ ]:
4. Remove the First and Last Elements:

In [28]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list without the first and last elements.
    """
    return lst[1:-1]  # Slicing to exclude the first and last elements

# Example usage
example_list = [1, 2, 3, 4, 5]
trimmed_list = remove_first_last(example_list)

# Display the result
print("Original list:", example_list)
print("List without first and last elements:", trimmed_list)


Original list: [1, 2, 3, 4, 5]
List without first and last elements: [2, 3, 4]


In [ ]:
5. Get the First n Elements:

In [30]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract.

    Returns:
        list: A new list containing the first n elements.
    """
    return lst[:n]  # Slicing to get the first n elements

# Example usage
example_list = [1, 2, 3, 4, 5]
n = 3
first_n_elements = get_first_n(example_list, n)

# Display the result
print("Original list:", example_list)
print(f"First {n} elements:", first_n_elements)


Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


In [ ]:
6. Extract Elements from the End:


In [32]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract from the end.

    Returns:
        list: A new list containing the last n elements.
    """
    return lst[-n:]  # Slicing to get the last n elements

# Example usage
example_list = [1, 2, 3, 4, 5]
n = 2
last_n_elements = get_last_n(example_list, n)

# Display the result
print("Original list:", example_list)
print(f"Last {n} elements:", last_n_elements)


Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


In [ ]:
7. Extract Elements in Reverse Order:


In [34]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last element and skipping one element in between.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every second element from the second-to-last, moving backward.
    """
    return lst[-2::-2]  # Start from second-to-last and step backward by 2

# Example usage
example_list = [1, 2, 3, 4, 5, 6]
reversed_skipped_list = reverse_skip(example_list)

# Display the result
print("Original list:", example_list)
print("Reversed with skips:", reversed_skipped_list)


Original list: [1, 2, 3, 4, 5, 6]
Reversed with skips: [5, 3, 1]


In [ ]:
4.3 Exercise on Nested List:

In [ ]:
1. Flatten a Nested List:

In [36]:
def flatten(lst):
    """
    Flattens a nested list into a single list with all elements in a single dimension.

    Parameters:
        lst (list): The nested list.

    Returns:
        list: A flattened version of the list.
    """
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(sublist)  # Extend the flat list with elements from the sublist
        else:
            flat_list.append(sublist)  # Append non-list elements directly
    return flat_list

# Example usage
example_nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(example_nested_list)

# Display the result
print("Original nested list:", example_nested_list)
print("Flattened list:", flattened_list)


Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


In [ ]:
2. Accessing Nested List Elements:

In [38]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
        lst (list): The nested list.
        indices (list): A list of indices representing the position to access.

    Returns:
        The element at the specified position in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]  # Navigate through the nested list using indices
    return element

# Example usage
example_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]  # Extracting element at row index 1, column index 2



In [ ]:
3. Sum of All Elements in a Nested List:

In [40]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
        lst (list): The nested list containing numbers.

    Returns:
        int: The sum of all numbers in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum elements in sublists
        else:
            total += item  # Add non-list elements directly
    return total

# Example usage
example_nested_list = [[1, 2], [3, [4, 5]], 6]
nested_sum = sum_nested(example_nested_list)

# Display the result
print("Original nested list:", example_nested_list)
print("Sum of all elements:", nested_sum)


Original nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [ ]:
4. Remove Specific Element from a Nested List:

In [42]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): The nested list.
        elem: The element to be removed.

    Returns:
        list: A modified list with the specified element removed.
    """
    modified_list = []
    
    for item in lst:
        if isinstance(item, list):
            # Recursively remove element from sublists
            modified_sublist = remove_element(item, elem)
            if modified_sublist:  # Only add non-empty lists
                modified_list.append(modified_sublist)
        elif item != elem:
            modified_list.append(item)  # Add non-matching elements

    return modified_list

# Example usage
example_nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
modified_list = remove_element(example_nested_list, element_to_remove)

# Display the result
print("Original nested list:", example_nested_list)
print(f"List after removing {element_to_remove}:", modified_list)


Original nested list: [[1, 2], [3, 2], [4, 5]]
List after removing 2: [[1], [3], [4, 5]]


In [ ]:
5. Find the Maximum Element in a Nested List:

In [44]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
        lst (list): The nested list.

    Returns:
        int/float: The maximum element in the nested list.
    """
    max_value = float('-inf')  # Initialize with the smallest possible number

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find max in sublists
        else:
            max_value = max(max_value, item)  # Compare non-list elements

    return max_value

# Example usage
example_nested_list = [[1, 2], [3, [4, 5]], 6]
max_element = find_max(example_nested_list)

# Display the result
print("Original nested list:", example_nested_list)
print("Maximum element:", max_element)

Original nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


In [ ]:
6. Count Occurrences of an Element in a Nested List:

In [46]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): The nested list.
        elem: The element to count.

    Returns:
        int: The count of occurrences of the specified element.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        elif item == elem:
            count += 1  # Increment count if element matches
    return count

# Example usage
example_nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
occurrences = count_occurrences(example_nested_list, element_to_count)

# Display the result
print("Original nested list:", example_nested_list)
print(f"Occurrences of {element_to_count}:", occurrences)


Original nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


In [ ]:
7. Flatten a List of Lists of Lists:

In [48]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
        lst (list): The deeply nested list.

    Returns:
        list: A flattened version of the list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            flat_list.append(item)  # Append non-list elements directly
    return flat_list

# Example usage
example_deep_nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(example_deep_nested_list)

# Display the result
print("Original deeply nested list:", example_deep_nested_list)
print("Flattened list:", flattened_list)


Original deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
8. Nested List Average:

In [50]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
        lst (list): The deeply nested list.

    Returns:
        list: A flattened version of the list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            flat_list.append(item)  # Append non-list elements directly
    return flat_list

def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): The nested list.

    Returns:
        float: The average of all elements in the nested list.
    """
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Example usage
example_nested_list = [[1, 2], [3, 4], [5, 6]]
nested_average = average_nested(example_nested_list)

# Display the result
print("Original nested list:", example_nested_list)
print("Average of all elements:", nested_average)

Original nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


In [ ]:
To - Do - NumPy

In [ ]:
Problem - 1: Array Creation:

In [52]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with a specified fill value
fill_value_array = np.full((3, 3), 7)  # Example fill value: 7

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

# Displaying the results
empty_array, ones_array, fill_value_array, zeros_like_array, ones_like_array, numpy_array


(array([[0.00000000e+000, 9.79307807e-312],
        [9.79307806e-312, 9.79307807e-312]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[0, 0],
        [0, 0]]),
 array([[1, 1],
        [1, 1]]),
 array([1, 2, 3, 4]))

In [ ]:
Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [54]:
# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)

# 2. Create a 3×3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

# 3. Create a 3×3 identity matrix
identity_matrix = np.eye(3)

# 4. Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()

# 5. Create a 10×10 array with random values and find the minimum and maximum values
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element (zero-based indexing)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

# 8. Create a 2D array with 1 on the border and 0 inside
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0  # Filling inside with zeros

# 9. Create an 8×8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Filling alternate rows and columns
checkerboard[::2, 1::2] = 1  # Filling alternate rows and columns

# Displaying results
array_range, matrix_3x3, identity_matrix, mean_value, (min_value, max_value), zero_array, reversed_arr, bordered_array, checkerboard

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 0.5554468992182728,
 (0.010229556643056359, 0.9799206889466724),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0, 4, 0, 0, 2, 1]),
 array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]]))

In [ ]:
Problem - 3: Array Operations:

In [56]:
# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (element-wise addition)
addition_result = x + y

# 2. Subtract the two arrays (element-wise subtraction)
subtraction_result = x - y

# 3. Multiply the array with any integer (let's choose 3)
multiplication_result = x * 3

# 4. Find the square of each element of the array
square_result = np.square(x)

# 5. Find the dot product
dot_v_w = np.dot(v, w)  # Dot product between v and w
dot_x_v = np.dot(x, v)  # Dot product between x and v
dot_x_y = np.dot(x, y)  # Dot product between x and y

# 6. Concatenate x and y along rows, and v and w along columns
concatenate_x_y_row = np.concatenate((x, y), axis=0)
concatenate_v_w_column = np.vstack((v, w))  # Stacking as columns

# 7. Attempt to concatenate x and v
try:
    concatenate_x_v = np.concatenate((x, v), axis=0)  # This should give an error
except ValueError as e:
    concatenate_x_v_error = str(e)  # Capturing the error message

# Displaying results
addition_result, subtraction_result, multiplication_result, square_result, dot_v_w, dot_x_v, dot_x_y, concatenate_x_y_row, concatenate_v_w_column, concatenate_x_v_error

(array([[ 6,  8],
        [10, 13]]),
 array([[-4, -4],
        [-4, -3]]),
 array([[ 3,  6],
        [ 9, 15]]),
 array([[ 1,  4],
        [ 9, 25]]),
 219,
 array([29, 77]),
 array([[19, 22],
        [50, 58]]),
 array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]),
 'all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)')

In [ ]:
Problem - 4: Matrix Operations:

In [58]:
# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^(-1) = I
A_inverse = np.linalg.inv(A)  # Compute inverse of A
identity_matrix = np.dot(A, A_inverse)  # A * A^(-1)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)  # Compute A * B
BA = np.dot(B, A)  # Compute B * A
AB_not_equal_BA = not np.array_equal(AB, BA)  # Check if AB is not equal to BA

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)  # Compute (AB)^T
BT_AT = np.dot(B.T, A.T)  # Compute B^T * A^T
transpose_property_holds = np.array_equal(AB_transpose, BT_AT)  # Check equality

# Solve the system of linear equations using inverse methods
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix
B_matrix = np.array([-1, -3, 9])  # Right-hand side values

# Solving for X using inverse method: X = A^(-1) * B
A_inverse_matrix = np.linalg.inv(A_matrix)  # Compute inverse of A_matrix
solution_X = np.dot(A_inverse_matrix, B_matrix)  # Compute solution X

# Displaying results
identity_matrix, AB_not_equal_BA, transpose_property_holds, solution_X


(array([[1.0000000e+00, 4.4408921e-16],
        [0.0000000e+00, 1.0000000e+00]]),
 True,
 True,
 array([ 2.,  1., -2.]))

In [ ]:
Experiment: How Fast is Numpy?

In [ ]:
1. Element-wise Addition:

In [60]:
import time

# Define the size of the lists/arrays
size = 1_000_000

# Generate two lists of size 1,000,000 with random values
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
list_time = end_time - start_time

# Generate two numpy arrays of size 1,000,000 with the same values
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()
array_sum = array1 + array2  # Vectorized operation
end_time = time.time()
numpy_time = end_time - start_time

# Display the results
list_time, numpy_time


(0.2503347396850586, 0.0026323795318603516)

In [ ]:
Element-wise Addition: Python Lists vs. NumPy Arrays
Time Taken:
Using Python Lists: 0.2503 seconds
Using NumPy Arrays: 0.0026 seconds
Observation:
NumPy arrays are nearly 95 times faster than Python lists for element-wise addition.
The primary reason for this is vectorization, where NumPy processes the entire array in one go instead of looping over elements one by one like Python lists.
NumPy also benefits from optimized memory management and low-level C implementations, making it significantly more efficient.

In [ ]:
2. Element-wise Multiplication

In [68]:
# Measure time for element-wise multiplication using Python lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
list_multiplication_time = end_time - start_time

# Measure time for element-wise multiplication using NumPy arrays
start_time = time.time()
array_product = array1 * array2  # Vectorized operation
end_time = time.time()
numpy_multiplication_time = end_time - start_time

# Display the results
list_multiplication_time, numpy_multiplication_time


(0.2683589458465576, 0.0)

In [ ]:
Element-wise Multiplication: Python Lists vs. NumPy Arrays
Time Taken:
Using Python Lists: 0.2684 seconds
Using NumPy Arrays: 0.0000 seconds (rounded to zero)
Observations:
NumPy is extremely fast for element-wise multiplication, so fast that the recorded time rounds to 0.0000 seconds.
This massive speed improvement is because:
NumPy leverages vectorized operations, which means the entire array is processed at once.
It utilizes highly optimized C-based computations, avoiding the overhead of Python loops.
Python lists, on the other hand, require explicit looping, making the process significantly slower.

In [ ]:
3. Dot Product

In [72]:
# Measure time for dot product using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
list_dot_time = end_time - start_time

# Measure time for dot product using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)  # Optimized dot product
end_time = time.time()
numpy_dot_time = end_time - start_time

# Display the results
list_dot_time, numpy_dot_time


(0.36113858222961426, 0.0)

In [ ]:
Dot Product: Python Lists vs. NumPy Arrays
Time Taken:
Using Python Lists: 0.3611 seconds
Using NumPy Arrays: 0.0000 seconds (rounded to zero)
Observations:
NumPy's dot product operation is so fast that the recorded time rounds to 0.0000 seconds.

The performance boost comes from:

Highly optimized matrix operations using BLAS (Basic Linear Algebra Subprograms) under the hood.
Efficient memory management that avoids unnecessary data copying.
Avoiding explicit Python loops, which are much slower.
Python lists, on the other hand, require looping through each pair of elements, making the dot product significantly slower.

In [ ]:
4. Matrix Multiplication

In [74]:
# Define matrix
matrix_size = 1000

# Generate two random 1000x1000 matrices using NumPy
matrix1_numpy = np.random.random((matrix_size, matrix_size))
matrix2_numpy = np.random.random((matrix_size, matrix_size))

# Measure time for matrix multiplication using NumPy (optimized)
start_time = time.time()
result_matrix_numpy = np.dot(matrix1_numpy, matrix2_numpy)  # Optimized matrix multiplication
end_time = time.time()
numpy_matrix_mult_time = end_time - start_time

# Display the result for NumPy matrix multiplication
numpy_matrix_mult_time


0.11065983772277832

In [ ]:
Matrix Multiplication: Python Lists vs. NumPy Arrays
Time Taken:
Using Python Lists: (Too slow, interrupted after 60 seconds)
Using NumPy Arrays: 0.1107 seconds
Observations:
NumPy is extremely optimized for matrix multiplication.

The massive speed improvement is due to:

NumPy's optimized linear algebra routines (backed by BLAS and LAPACK libraries).
Vectorized operations, avoiding slow Python loops.
Efficient memory access, ensuring fast computation.
Python lists were so slow that the process was forcefully stopped after 60 seconds, proving that NumPy is essential for large-scale matrix computations.